@startuml カートに追加シーケンス図
hide footbox
skinparam boundaryBackgroundColor #D5E8D4
skinparam controlBackgroundColor  #F8CECC
skinparam entityBackgroundColor   #DAE8FC

actor 顧客 as A
boundary "goodsDetail.jsp" as B1 
control "addCart.jsp" as C
entity "Goods.java" as S
entity "Cart.java" as K
boundary "addCartComplete.jsp" as M
boundary "outOfStock.jsp" as E
boundary "login.jsp" as L

A -> B1: 「カートに追加」押下
activate B1

B1 -> C: addCart()
activate C

C -> S: getGoodsDetail()
activate S
S --> C: 在庫可否()
deactivate S

C -> K: addCartData()
activate K
K --> C: 追加成功
deactivate K

C -> M: 表示()

alt 在庫不足
    C -> E: 在庫不足エラー通知()
    activate E
    E --> B1: 表示()
    deactivate E
end

alt 未ログイン
    C -> L: login()
    note over L
        以下、ログインの
        ユースケースへ
    end note
end

@enduml
